dist: xenial
language: python
cache: pip
install: make setup
stages:
  - lint
  - test
  - coverage
jobs:
  include:
    - stage: lint
      before_script: pip install black
      script: make lint
      python: '3.7'
    - stage: test
      python: '2.7'
      script: make test
    - stage: test
      python: '3.5'
      script: make test
    - stage: test
      python: '3.6'
      script: make test
    - stage: test
      python: '3.7'
      script: make test
    - stage: coverage
      python: '3.7'
      script: codecov