dist: xenial
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
cache: pip
install: make setup
script: make ci
after_success: if [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then codecov; fi
notifications:
  email: false